### ISSUE TITLE
GR2 decompression can fail if backref_size > backref_offset

### ISSUE THREAD

**Issue by Arbos** [berenm/game-data-reverse-engineering#1]
Hi. For my [MDB/GR2 <-> FBX converter](https://github.com/Arbos/nwn2mdk) and my [FL](https://forum.neverwintervault.org/t/project-fl/409/13) project I was working on decompressing the NWN2 GR2 files. By chance I found this repository where you have reverse engineered the decompression algorithm. I have tried it and found that it can fail if backref_size > backref_offset because when executing this line:

`std::memmove(dbuf, dbuf - backref_offset, backref_size);`

it tries to copy bytes from beyond what has been written to the decompressed buffer. In particular, with backref_offset == 1 and backref_size == 5 it failed on my tests. I have fixed this bug and have tried like 20 GR2 files, comparing byte by byte the output of your implementation with the output of GrannyDecompressData (using granny32.dll from NWN2 install) and they are equal!

**Comment by berenm** [comment]
Nice! I believe I tested the algorithm on many GR2 files, but it was a long time ago, and I may have missed some corner cases.

So, if I understand correctly, the copy should repeat the same bytes if the size is larger than the offset? ie: In the case offset == 1 and size == 5, it should repeat 5 times the last byte, right?

**Comment by berenm** [comment]
BTW, I had some cleaned-up implementation of the decompression algorithm as well as converters from GR2 to YAML there: https://github.com/berenm/xoreos-tools/tree/wip/granny-decoder

I wanted to make a PR to xoreos-tools, but didn't find the time to properly rewrite them to fit in the project codebase.

**Comment by Arbos** [comment]
Sorry, I closed by error.

> So, if I understand correctly, the copy should repeat the same bytes if the size is larger than the offset? ie: In the case offset == 1 and size == 5, it should repeat 5 times the last byte, right?

Right, it behaves as a Run-length decoding.

I looked at the clean-up implementation and this bug is fixed. I will use that implementation (under Boost Software License, Version 1.0). You can close this issue if you want.
